// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using nCov1._0.Models;

namespace nCov1._0.Migrations
{
    [DbContext(typeof(T))]
    [Migration("20200908194704_AddItems")]
    partial class AddItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("nCov1._0.Models.NCovStateData", b =>
                {
                    b.Property<string>("SdCode")
                        .HasColumnName("sdCode")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("DName")
                        .IsRequired()
                        .HasColumnName("dName")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<double>("LatCoordinates")
                        .HasColumnType("double precision");

                    b.Property<double>("LongCoordinates")
                        .HasColumnType("double precision");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasColumnName("sName")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<long>("TotalCases")
                        .HasColumnType("bigint");

                    b.HasKey("SdCode")
                        .HasName("PK__tmp_ms_x__A3801A317F3F7A1E");

                    b.ToTable("nCovStateData");
                });
#pragma warning restore 612, 618
        }
    }
}
