// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nCov1._0.Models;

namespace nCov1._0.Migrations
{
    [DbContext(typeof(nCov10Context))]
    [Migration("20230107094645_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("nCov1._0.Models.NCovStateData", b =>
                {
                    b.Property<string>("SdCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LatCoordinates")
                        .HasColumnType("float");

                    b.Property<double>("LongCoordinates")
                        .HasColumnType("float");

                    b.Property<string>("SName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TotalCases")
                        .HasColumnType("bigint");

                    b.HasKey("SdCode");

                    b.ToTable("NCovStateData");
                });
#pragma warning restore 612, 618
        }
    }
}
